### PR TITLE
[ISSUE] Title Responsiveness

### PR DESCRIPTION
**Pull request by Sanjana-027**
Hello,
There was an issue in Title responsiveness as shown in below image:-
WhatsApp Image 2021-10-06 at 6 04 35 PM
-
**I have fixed this issue as shown in below image:-**
WhatsApp Image 2021-10-06 at 6 52 46 PM

If any more modifications required then, please let me know.
Thanks!

### CODE REVIEW

**Comment by Sanjana-027** [comment]
@saswatsamal Please check it once.

**Review by saswatsamal — APPROVED** [review]
Perfect!

**Comment by saswatsamal** [comment]
Merged! 🎉

**Comment by Sanjana-027** [comment]
Thanks!

**Pull request merged**
